export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About',
    headline: 'Work with us to make a difference',
    description: 'Get access to out exclusive app, to upload and see other users videos about their experiences.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../../assets/images/eb-1.jpg'),
    alt: 'Bands',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'people',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'See other people\'s videos',
    headline: 'Get ideas to make a difference',
    description: 'See other people\'s videos about their experiences and get ideas to make a difference.',
    buttonLabel: 'Workouts',
    imgStart: false,
    img: require('../../../assets/images/train.png'),
    alt: 'Bands',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'upload',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Upload',
    headline: 'Upload your own video',
    description: 'Upload your own video about your experience to help other people to make a difference.',
    buttonLabel: 'Sign Up',
    imgStart: true,
    img: require('../../../assets/images/uploadvid.png'),
    alt: 'Bands',
    dark: true,
    primary: true,
    darkText: false,
}